apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-prometheus-example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi-prometheus-example
  template:
    metadata:
      labels:
        app: fastapi-prometheus-example
    spec:
      containers:
      - name: fastapi-prometheus-example
        image: fastapi-prometheus-example:v0.0.8.pid
        imagePullPolicy: Never  # Set imagePullPolicy to Never
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: fastapi-prometheus-example-clusterip
spec:
  selector:
    app: fastapi-prometheus-example
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: fastapi-prometheus-example-nodeport
  labels:
    app.kubernetes.io/instance: fastapi-example
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: fastapi-example
    module: fastapi-example
spec:
  selector:
    app: fastapi-prometheus-example
  ports:
    - name: metrics
      protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30390
  type: NodePort
# kubectl apply -f deployment.yaml
# kubectl port-forward -n=default svc/fastapi-prometheus-example-nodeport 38000:8000
