apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.nginx.fullname  }}
  labels:
    app: {{ .Values.nginx.label.name }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: {{ .Values.nginx.label.name }}
