name: myenv
channels:
  - conda-forge
  - defaults
dependencies:
  - prometheus-fastapi-instrumentator
  - uvicorn
  - opentelemetry-distro
  - opentelemetry-instrumentation-fastapi
  - opentelemetry-instrumentation-logging
  - opentelemetry-exporter-otlp