name: CI

on:
  push:
    branches:
      - main

jobs:
  echo-env:
    runs-on: ubuntu-latest
    steps:
    - name: Print a greeting
      env:
        MY_VAR: Hi there! My name is
        FIRST_NAME: Regina
      run: |
        echo $MY_VAR $FIRST_NAME.

    - name: Print commit ID
      run: echo "git_hash=$(git rev-parse --short "$GITHUB_SHA")" >> $GITHUB_HASH


  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./app_fastapi
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Check dirs and files
      run: pwd && ls

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
    
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        push: true
        context: "{{defaultContext}}:app_fastapi"
        file: Dockerfile
        tags: 2108248/github-images:fastapi.test