name: CI

on:
  push:
    branches:
      - main

jobs:
  echo-env:
    runs-on: ubuntu-latest
    steps:
    - name: Print a greeting
      env:
        MY_VAR: Hi there! My name is
        FIRST_NAME: Regina
      run: |
        echo $MY_VAR $FIRST_NAME.
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build and push Docker image
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./app_fastapi/Dockerfile
        push: true
        tags: 2108248/fastapi-prometheus-example:v0.0.7.errorhandler