name: CI

on:
  push:
    branches:
      - main

jobs:
  echo-env:
    runs-on: ubuntu-latest
    steps:
    - name: Print a greeting
      env:
        MY_VAR: Hi there! My name is
        FIRST_NAME: Regina
      run: |
        echo $MY_VAR $FIRST_NAME.

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        push: true
        file: ./app_fastapi/Dockerfile
        tags: 2108248/github-images:fastapi.v0.0.7.errorhandler